namespace :catalog do
  desc "Seed the reference muscle and equipment taxonomies (idempotent)"
  task seed_taxonomy: :environment do
    report = Catalog::TaxonomySeeder.call
    puts "Seeded catalog taxonomy — #{report}"
    puts "Totals: #{Muscle.count} muscles, #{Equipment.count} equipment"
  end

  desc "Import the provider exercise catalog (idempotent; never touches custom exercises)"
  task sync: :environment do
    provider = Catalog::Providers::WorkoutX.new

    unless provider.configured?
      abort <<~MSG
        WORKOUTX_API_KEY is not set.

        Set it in the environment for this process only. It belongs in Railway
        variables in production and must never be committed.
      MSG
    end

    puts "Seeding taxonomy first so provider values resolve to stable keys..."
    Catalog::TaxonomySeeder.call

    puts "Syncing #{provider.source}..."
    run = Catalog::Sync.call(provider: provider)

    puts "Finished with status #{run.status} in #{run.duration_seconds.round(1)}s"
    puts "  fetched:     #{run.fetched_count}"
    puts "  created:     #{run.created_count}"
    puts "  updated:     #{run.updated_count}"
    puts "  deactivated: #{run.deactivated_count}"
    puts "  rejected:    #{run.rejected_count}"
    puts "  notes:       #{run.error_summary}" if run.error_summary.present?

    # Translation belongs to synchronization, never to a user request, so it
    # runs here rather than being triggered by a read.
    puts
    Rake::Task["catalog:translate"].invoke
  end

  desc "Generate Italian for catalog exercises whose English changed (idempotent)"
  task translate: :environment do
    adapter = Catalog::Translation::GoogleAdapter.new

    unless adapter.configured?
      puts "Skipping translation: GOOGLE_TRANSLATE_API_KEY is not set."
      puts "Italian falls back to English until a provider is configured."
      next
    end

    puts "Translating with #{adapter.name}..."
    report = Catalog::TranslateCatalog.call(adapter: adapter)

    puts "Considered #{report.considered} exercises"
    puts "  translated:      #{report.translated}"
    puts "  already current: #{report.skipped}"
    puts "  human-reviewed:  #{report.protected_count} (left alone)"
    puts "  without english: #{report.no_source}"
    puts "  failed:          #{report.failed}"
    puts "  characters sent: #{report.characters}"
  end

  desc "Show exactly what a catalog reset would delete. Deletes nothing. SCOPE=legacy|catalog|everything"
  task reset_plan: :environment do
    scope = ENV.fetch("SCOPE", "legacy").to_sym
    report = Catalog::ResetPlan.call(scope: scope)

    puts "Environment: #{Rails.env} / #{ENV.fetch('RAILWAY_ENVIRONMENT_NAME', 'local')}"
    puts "Database:    #{ActiveRecord::Base.connection_db_config.database}"
    puts
    puts report
    puts

    if report.destroys_client_data?
      puts "!! This would delete #{report.set_logs} logged sets and #{report.exercise_logs} exercise logs."
      puts "!! Training history cannot be regenerated by re-running a sync."
      puts
    end

    if report.destructive?
      puts "To perform it:"
      puts "  bin/rails catalog:reset SCOPE=#{report.scope} CONFIRM_EXERCISES=#{report.exercises}"
    else
      puts "Nothing to delete in this scope."
    end
  end

  desc "Delete catalog exercises so an import can replace them. Requires CONFIRM_EXERCISES to match the plan."
  task reset: :environment do
    scope = ENV.fetch("SCOPE", "legacy").to_sym
    confirm = ENV["CONFIRM_EXERCISES"]

    if confirm.blank?
      abort <<~MSG
        Refusing to run without CONFIRM_EXERCISES.

        Review the plan first:
          bin/rails catalog:reset_plan SCOPE=#{scope}

        then repeat the exercise count back:
          bin/rails catalog:reset SCOPE=#{scope} CONFIRM_EXERCISES=<count>

        The count must still match when this runs, so a reset cannot act on a
        report that has gone stale.
      MSG
    end

    result = Catalog::ResetCatalog.call(scope: scope, expected_exercises: Integer(confirm))
    puts "Deleted #{result.deleted} exercises (scope: #{scope})."
    puts result.report
  rescue Catalog::ResetCatalog::CountMismatch => e
    abort "Refusing to reset. #{e.message}"
  end

  desc "Fold duplicate muscle rows onto their canonical key (idempotent, no provider calls)"
  task merge_muscle_aliases: :environment do
    before = Muscle.count
    report = Catalog::MergeMuscleAliases.call
    puts report
    puts "muscles: #{before} -> #{Muscle.count}"
  end
end
