module Catalog
  # Reports exactly what a catalog reset would delete, without deleting it.
  #
  # Plan §12 requires inspecting foreign-key dependencies and reporting the
  # precise blast radius before anything destructive runs. The cascade is not
  # obvious from the outside:
  #
  #   Exercise -> workout_exercises -> exercise_logs -> set_logs
  #
  # so removing a single exercise can destroy a client's logged weights and
  # repetitions. That is the number an operator needs to see before deciding,
  # and it is the one this puts first.
  class ResetPlan
    # What counts as "the catalog to clear":
    #
    #   :legacy   the hand-seeded exercises that predate the provider, i.e.
    #             catalog rows with no source. The default, because this is
    #             what a provider import is meant to replace.
    #   :catalog  every non-custom exercise, provider rows included. Re-syncing
    #             afterwards recreates them with new ids, so prefer :legacy
    #             unless the intent really is to start from nothing.
    #   :everything  also coach-owned custom exercises. Never a default: that
    #             is a coach's own work, not catalog content.
    SCOPES = %i[legacy catalog everything].freeze

    Report = Data.define(
      :scope, :exercises, :workout_exercises, :exercise_logs, :set_logs,
      :translations, :muscle_links, :equipment_links, :media,
      :emptied_workouts, :custom_exercises
    ) do
      def destructive? = exercises.positive?

      # The one that should stop someone: logged training data cannot be
      # regenerated by re-running a sync.
      def destroys_client_data? = set_logs.positive? || exercise_logs.positive?

      def to_s
        <<~TEXT.strip
          scope: #{scope}
            exercises to delete:   #{exercises}
            workout_exercises:     #{workout_exercises}
            exercise_logs:         #{exercise_logs}
            set_logs:              #{set_logs}   <- client-logged weights and reps
            translations:          #{translations}
            muscle links:          #{muscle_links}
            equipment links:       #{equipment_links}
            media references:      #{media}
            workouts left empty:   #{emptied_workouts}
            custom exercises kept: #{custom_exercises}
        TEXT
      end
    end

    def self.call(...) = new(...).call

    def initialize(scope: :legacy)
      raise ArgumentError, "unknown scope #{scope.inspect}" unless SCOPES.include?(scope.to_sym)

      @scope = scope.to_sym
    end

    def call
      ids = target_ids
      workout_exercise_ids = WorkoutExercise.where(exercise_id: ids).pluck(:id)
      exercise_log_ids = ExerciseLog.where(workout_exercise_id: workout_exercise_ids).pluck(:id)

      Report.new(
        scope: @scope,
        exercises: ids.size,
        workout_exercises: workout_exercise_ids.size,
        exercise_logs: exercise_log_ids.size,
        set_logs: SetLog.where(exercise_log_id: exercise_log_ids).count,
        translations: ExerciseTranslation.where(exercise_id: ids).count,
        muscle_links: ExerciseMuscle.where(exercise_id: ids).count,
        equipment_links: ExerciseEquipment.where(exercise_id: ids).count,
        media: ExerciseMedium.where(exercise_id: ids).count,
        emptied_workouts: emptied_workout_count(workout_exercise_ids),
        custom_exercises: @scope == :everything ? 0 : Exercise.custom.count
      )
    end

    # The relation the reset will actually delete. Shared with ResetCatalog so
    # the plan and the deletion can never disagree about what is in scope.
    def target
      case @scope
      when :legacy then Exercise.catalog.where(source: nil)
      when :catalog then Exercise.catalog
      when :everything then Exercise.all
      end
    end

    private

    def target_ids = @target_ids ||= target.pluck(:id)

    # A workout whose every exercise is being removed is left with nothing in
    # it. Nothing deletes it, so it becomes an empty shell a coach has to
    # notice and fix.
    def emptied_workout_count(workout_exercise_ids)
      return 0 if workout_exercise_ids.empty?

      # reorder(nil) because WorkoutExercise carries a default_scope ordering by
      # position, and Postgres rejects SELECT DISTINCT with an ORDER BY column
      # that is not in the select list.
      affected = WorkoutExercise.where(id: workout_exercise_ids)
                                .reorder(nil)
                                .distinct
                                .pluck(:workout_id)
      return 0 if affected.empty?

      surviving = WorkoutExercise.where(workout_id: affected)
                                 .where.not(id: workout_exercise_ids)
                                 .reorder(nil)
                                 .distinct
                                 .pluck(:workout_id)

      (affected - surviving).size
    end
  end
end
